/* Test-only frontend-tool state layout. */
#ifndef POSTGAMMA_TEST_TOOL_STATE_LAYOUT_H
#define POSTGAMMA_TEST_TOOL_STATE_LAYOUT_H

typedef enum PostgammaToolStateSlot
{
	POSTGAMMA_TOOL_STATE_SLOT_TARGET = 0,
	POSTGAMMA_TOOL_STATE_SLOT_OWNER = 1,
	POSTGAMMA_TOOL_STATE_SLOT_COUNT = 2
} PostgammaToolStateSlot;

#define POSTGAMMA_TOOL_STATE_BYTES 80
#define POSTGAMMA_TOOL_STATE_ALIGNMENT 8

#endif /* POSTGAMMA_TEST_TOOL_STATE_LAYOUT_H */
