#!/usr/bin/env python3
"""Generate mkdocstrings directives from the frozen Python API inventory."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


class DocumentationError(RuntimeError):
    """Raised when the Python API and documentation inventory diverge."""


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise DocumentationError(f"cannot read {path}: {error}") from error
    if not isinstance(value, dict):
        raise DocumentationError(f"{path} must contain an object")
    return value


def documented_members(document: dict[str, Any]) -> list[dict[str, str]]:
    groups = document.get("groups")
    if not isinstance(groups, list) or not groups:
        raise DocumentationError("Python documentation groups must be nonempty")
    members: list[dict[str, str]] = []
    for group in groups:
        if (
            not isinstance(group, dict)
            or not isinstance(group.get("title"), str)
            or not isinstance(group.get("description"), str)
            or not isinstance(group.get("members"), list)
        ):
            raise DocumentationError("invalid Python documentation group")
        for member in group["members"]:
            if (
                not isinstance(member, dict)
                or not isinstance(member.get("name"), str)
                or member.get("render") not in {"attribute", "object"}
                or not isinstance(member.get("inherited_members", False), bool)
            ):
                raise DocumentationError("invalid Python documentation member")
            if member["render"] == "attribute" and not isinstance(
                member.get("summary"), str
            ):
                raise DocumentationError(
                    f"attribute {member['name']} has no documentation summary"
                )
            members.append(member)
    names = [member["name"] for member in members]
    if len(names) != len(set(names)):
        raise DocumentationError("Python documentation contains duplicate members")
    return members


def validate(
    baseline: dict[str, Any], documentation: dict[str, Any]
) -> tuple[list[str], list[dict[str, Any]]]:
    if baseline.get("kind") != "postgamma.python-release-baseline":
        raise DocumentationError("unsupported Python API baseline")
    if documentation.get("kind") != "postgamma.python-api-documentation":
        raise DocumentationError("unsupported Python documentation inventory")
    exports = baseline.get("public_exports")
    if not isinstance(exports, list) or not all(
        isinstance(name, str) for name in exports
    ):
        raise DocumentationError("Python public export baseline is invalid")
    if len(exports) != len(set(exports)):
        raise DocumentationError("Python public export baseline has duplicates")
    members = documented_members(documentation)
    documented = {member["name"] for member in members}
    expected = set(exports)
    if documented != expected:
        raise DocumentationError(
            "Python API documentation mismatch: "
            f"missing={sorted(expected - documented)}, "
            f"stale={sorted(documented - expected)}"
        )
    return exports, documentation["groups"]


def render(groups: list[dict[str, Any]]) -> str:
    lines = [
        "<!-- Generated by buildsys/generate_python_api_docs.py; do not edit. -->",
        "",
    ]
    for group in groups:
        lines.extend([f"## {group['title']}", "", group["description"], ""])
        attributes = [
            member for member in group["members"] if member["render"] == "attribute"
        ]
        if attributes:
            lines.extend(["| Name | Meaning |", "| --- | --- |"])
            for member in attributes:
                lines.append(f"| `postgamma.{member['name']}` | {member['summary']} |")
            lines.append("")
        for member in group["members"]:
            if member["render"] != "object":
                continue
            lines.extend(
                [
                    f"::: postgamma.{member['name']}",
                    "    options:",
                    "      inherited_members: "
                    + str(member.get("inherited_members", False)).lower(),
                    "      members: true",
                    "      show_root_heading: true",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument(
        "--baseline", default="manifests/api/python-api-v1.json", type=Path
    )
    parser.add_argument(
        "--documentation", default="docs/reference/python-api.json", type=Path
    )
    parser.add_argument(
        "--output", default="build/docs/generated/python-api.md", type=Path
    )
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        baseline = load_json((root / args.baseline).resolve())
        documentation = load_json((root / args.documentation).resolve())
        exports, groups = validate(baseline, documentation)
    except DocumentationError as error:
        parser.error(str(error))
    output = (root / args.output).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(groups), encoding="utf-8")
    report = {
        "schema_version": 1,
        "kind": "postgamma.python-api-documentation-evidence",
        "status": "pass",
        "public_export_count": len(exports),
        "group_count": len(groups),
    }
    report_path = output.with_suffix(".json")
    report_path.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(
        f"Python documentation: {len(exports)} public exports in {len(groups)} groups"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
